CREATE TABLE IF NOT EXISTS COUNTRIES
                       (CODE VARCHAR(2) PRIMARY KEY,
                        NAME VARCHAR(128),
                        PHONECODE VARCHAR(128) );
CREATE INDEX IF NOT EXISTS COUNTRYNAME_INDEX ON COUNTRIES(NAME);

CREATE TABLE IF NOT EXISTS COUNTRIES_COPY
                       (CODE VARCHAR(2) PRIMARY KEY,
                        NAME VARCHAR(128),
                        PHONECODE VARCHAR(128) );
CREATE INDEX IF NOT EXISTS COUNTRY_COPYNAME_INDEX ON COUNTRIES_COPY(NAME);